# Generated by Django 3.1.1 on 2020-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=50, verbose_name='Document'),
        ),
    ]
